import os
import re

def build_content_studio():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    src_dir = os.path.join(base_dir, 'src')
    dist_file = os.path.join(base_dir, 'index.html')

    print(f"Building Content Studio single-file HTML bundle from {src_dir} -> {dist_file}")

    # 1. Read and clean modular JS files
    def clean_module(file_path):
        with open(file_path, 'r', encoding='utf-8') as f:
            code = f.read()
        # Remove import statements
        code = re.sub(r'import\s+[^;]+;', '', code)
        # Strip export statements
        code = re.sub(r'export\s+(const|let|var)\s+', r'\1 ', code)
        code = re.sub(r'export\s+(async\s+)?function\s+', r'\1function ', code)
        code = re.sub(r'export\s+default\s+', '', code)
        return code

    studio_data_js = clean_module(os.path.join(src_dir, 'data', 'studio_data.js'))
    math_engine_js = clean_module(os.path.join(src_dir, 'components', 'math_engine.js'))
    equation_modal_js = clean_module(os.path.join(src_dir, 'components', 'equation_modal.js'))
    reviewer_studio_js = clean_module(os.path.join(src_dir, 'components', 'reviewer_studio.js'))
    quiz_studio_js = clean_module(os.path.join(src_dir, 'components', 'quiz_studio.js'))
    calendar_studio_js = clean_module(os.path.join(src_dir, 'components', 'calendar_studio.js'))
    json_hub_js = clean_module(os.path.join(src_dir, 'components', 'json_hub.js'))
    app_js = clean_module(os.path.join(src_dir, 'app.js'))

    bundled_js = f"""
    /* =========================================================================
       TagSci Content Studio - Bundled Application Logic (Auto-generated by build.py)
       ========================================================================= */
    {studio_data_js}

    {math_engine_js}

    {equation_modal_js}

    {reviewer_studio_js}

    {quiz_studio_js}

    {calendar_studio_js}

    {json_hub_js}

    {app_js}
    """

    # 2. Read src/index.html template
    with open(os.path.join(src_dir, 'index.html'), 'r', encoding='utf-8') as f:
        html = f.read()

    # 3. Replace module script tag with inlined bundled JS
    target_script = '<script type="module" src="./app.js"></script>'
    if target_script in html:
        html = html.replace(target_script, f'<script>\n{bundled_js}\n</script>')
    else:
        html = re.sub(r'<script\s+type="module"\s+src="./app.js"></script>', lambda m: f'<script>\n{bundled_js}\n</script>', html)

    # 4. Write Content Studio/index.html
    with open(dist_file, 'w', encoding='utf-8') as f:
        f.write(html)

    print(f"Successfully generated standalone Content Studio at {dist_file}")

if __name__ == '__main__':
    build_content_studio()
